development:
  adapter: postgresql
  encoding: unicode
  database: my_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: my_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: my_production
  host: localhost
  pool: 5
